sample_ror_admin/config/routes.rb
SnapshotApp::Application.routes.draw do
  resources :topics

  resources :snapshots

  devise_for :users

  root :to => 'snapshots#index'

end

sample_ror_admin/app/models/snapshot.rb
class Snapshot < ActiveRecord::Base
  attr_accessible :abstract, :authors, :cover_image, :displayed, :disporder, \
                  :download_count, :full_image1, :full_image2, :full_image3, \
                  :full_pdf, :popularity, :publication_date, :thumb_image, :title, \
                  :topicizations_attributes
  
  mount_uploader :thumb_image, SnapshotUploader
  mount_uploader :cover_image, SnapshotUploader
  mount_uploader :full_image1, SnapshotUploader
  mount_uploader :full_image2, SnapshotUploader
  mount_uploader :full_image3, SnapshotUploader
  mount_uploader :full_pdf, SnapshotUploader
  
  has_many :topicizations, :dependent => :destroy
  has_many :topics, :through => :topicizations
  
  accepts_nested_attributes_for :topicizations, :allow_destroy => true
  
end

sample_ror_admin/app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :displayed, :disporder, :name
  
  has_many :topicizations, :dependent => :destroy
  has_many :snapshots, :through => :topicizations
  
end

sample_ror_admin/app/models/topicization.rb
class Topicization < ActiveRecord::Base
  attr_accessible :created_at, :snapshot_id, :topic_id
  
  belongs_to :snapshot
  belongs_to :topic
end

sample_ror_admin/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

sample_ror_admin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :auth_user

  private
  def auth_user
    
    unless user_signed_in?
      authenticate_user!
    end
    
  end

  private 
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

sample_ror_admin/app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
  # GET /snapshots
  # GET /snapshots.json
  def index
    
    logger.debug "params" + params[:topic].to_s + "." + params[:action].to_s
    
    if params[:topic]
      topic = Topic.find(params[:topic])
      @snapshots = topic.topicizations.collect { |a| a.snapshot }
    else
      @snapshots = Snapshot.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snapshots }
    end
  end

  # GET /snapshots/1
  # GET /snapshots/1.json
  def show
    @snapshot = Snapshot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snapshot }
    end
  end

  # GET /snapshots/new
  # GET /snapshots/new.json
  def new
    @snapshot = Snapshot.new
    @snapshot.topicizations.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snapshot }
    end
  end

  # GET /snapshots/1/edit
  def edit
    @snapshot = Snapshot.find(params[:id])
  end

  # POST /snapshots
  # POST /snapshots.json
  def create
    @snapshot = Snapshot.new(params[:snapshot])

    respond_to do |format|
      if @snapshot.save
        format.html { redirect_to @snapshot, notice: 'Snapshot was successfully created.' }
        format.json { render json: @snapshot, status: :created, location: @snapshot }
      else
        format.html { render action: "new" }
        format.json { render json: @snapshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snapshots/1
  # PUT /snapshots/1.json
  def update
    @snapshot = Snapshot.find(params[:id])

    respond_to do |format|
      if @snapshot.update_attributes(params[:snapshot])
        format.html { redirect_to @snapshot, notice: 'Snapshot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snapshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snapshots/1
  # DELETE /snapshots/1.json
  def destroy
    @snapshot = Snapshot.find(params[:id])
    @snapshot.destroy

    respond_to do |format|
      format.html { redirect_to snapshots_url }
      format.json { head :no_content }
    end
  end
end

sample_ror_admin/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
end

sample_ror_admin/app/helpers/application_helper.rb
module ApplicationHelper
  
  def getTopics
    @topics = Topic.all
    return @topics
  end

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
  
end

sample_ror_admin/app/helpers/snapshots_helper.rb
module SnapshotsHelper
end

sample_ror_admin/app/helpers/topics_helper.rb
module TopicsHelper
end

sample_ror_admin/app/views/layouts/_actions_tab.html.erb
<ul class="nav nav-pills">
  
  <li <% if params[:controller] == "snapshots" && params[:action] == "index" && !params.has_key?(:topic) %> class="active" <% end %> >
    <a href="/snapshots">All Snapshots</a>
  </li>
  <li <% if params[:controller] == "snapshots" && params[:action] == "new" %> class="active" <% end %> >
    <%= link_to 'Add Snapshot', new_snapshot_path %>
  </li>
  <li <% if params[:controller] == "topics" && params[:action] == "index" %> class="active" <% end %> >
    <a href="/topics">All Topics</a>
  </li>
  <li <% if params[:controller] == "topics" && params[:action] == "new" %> class="active" <% end %> >
    <%= link_to 'Add Topic', new_topic_path %>
  </li>
</ul>

sample_ror_admin/app/views/layouts/_left_nav.html.erb
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">
                <h5>Topics</h5>
              </li>
              <li <% if params[:controller] == "topics" %> class="active" <% end %> >
                <a href="/topics">Manage Topics</a>
              </li>
              <li class="nav-header">
                <h5>Snapshots</h5>
              </li>
              <li <% if params[:controller] == "snapshots" && params[:action] == "index" && !params.has_key?(:topic) %> class="active" <% end %> >
                <a href="/snapshots">All</a>
              </li>
              
              <% @topics.each do |topic| %>
              <li <% if params[:topic] == topic.id.to_s %> class="active" <% end %> >
                <a href="/snapshots?topic=<%= topic.id %>"><%= topic.name %></a>
              </li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div>
<!-- end of left_nav -->

sample_ror_admin/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

sample_ror_admin/app/views/layouts/_top_nav.html.erb
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Backend_sample</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right" >
            <% if user_signed_in? %>
              Hi, <a class="navbar-link"><%= current_user.email %></a>
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
              <%= link_to "Sign in", new_user_session_path %>
              <%= link_to "Sign up", new_user_registration_path %>
            <% end %></p>
            <ul class="nav">
              <li class="active"><a href="/snapshots">Home</a></li>
              <% if user_signed_in? %>
              <li><a href="/recent">Most Recent</a></li>
              <li><a href="/favorites">Favorites</a></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
<!-- end of top_nav -->

sample_ror_admin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnapshotApp</title>
  <%= stylesheet_link_tag    "application", 
                              "bootstrap",
                              "bootstrap-responsive" %>
  <%= javascript_include_tag "application", "jquery", "jquery_ujs"%>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/top_nav' %>

  <% if user_signed_in? %>

  <div class="container-fluid">
    <div class="row-fluid">
      
      <%= render 'layouts/left_nav', :collection => getTopics %>
      
      <div class="span9">
        
        <%= render 'layouts/actions_tab' %>
        <%= render 'layouts/messages' %>
        <%= yield %>
        
      </div>
      
    </div>
  </div>

  <% else %>
    <center>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </center>
  <% end %>

</body>
</html>

sample_ror_admin/app/views/snapshots/_form.html.erb
<%= simple_form_for(@snapshot) do |f| %>
  <% if @snapshot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snapshot.errors.count, "error") %> prohibited this snapshot from being saved:</h2>

      <ul>
      <% @snapshot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :publication_date %>
  <%= f.input :disporder %>
  <%= f.input :displayed %>
  <%= f.input :authors %>
  <%= f.input :abstract, :input_html => {:cols => 40, :rows => 10, :style => "margin: 0px 0px 10px; width: 371px; height: 116px; "} %>
  <%= f.input :popularity %>
  <%= f.input :download_count %>
  
  <div class="field">
    <label>Under Topics : </label>
    <%= f.simple_fields_for :topicizations do |builder| %>
      <%= render 'topicization_fields', :f => builder %>
    <% end %>
    <p><label></label><%= link_to_add_fields "Add Topic", f, :topicizations %></p>
  </div><br />
  
  <table cellpadding="10px">
    <tr>
      <td>
        <%= f.input :thumb_image, :as => :file, :input_html => {:onchange => "showPreview(this,'thumb_image');"} %>
      </td>
      <td>
        <% if @snapshot.thumb_image? %>
          <%= image_tag @snapshot.thumb_image, :id => "thumb_image", :width=>"150px" %>
        <% else %>
          <%= image_tag("no_img_160_120.gif", :id => "thumb_image", :alt => "uploaded image") %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
      <%= f.input :cover_image, :as => :file, :input_html => {:onchange => "showPreview(this,'cover_image');"} %>
    </td>
      <td>
        <% if @snapshot.cover_image? %>
          <%= image_tag @snapshot.cover_image, :id => "cover_image", :width=>"150px" %>
        <% else %>
          <%= image_tag("no_img_160_120.gif", :id => "cover_image", :alt => "uploaded image") %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.input :full_image1, :as => :file, :input_html => {:onchange => "showPreview(this,'full_image1');"}  %>
      </td>
      <td>
        <% if @snapshot.full_image1? %>
          <%= image_tag @snapshot.full_image1, :id => "full_image1", :width=>"150px" %>
        <% else %>
          <%= image_tag("no_img_160_120.gif", :id => "full_image1", :alt => "uploaded image") %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.input :full_image2, :as => :file, :input_html => {:onchange => "showPreview(this,'full_image2');"}  %>
      </td>
      <td>
        <% if @snapshot.full_image2? %>
          <%= image_tag @snapshot.full_image2, :id => "full_image2", :width=>"150px" %>
        <% else %>
          <%= image_tag("no_img_160_120.gif", :id => "full_image2", :alt => "uploaded image") %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.input :full_image3, :as => :file, :input_html => {:onchange => "showPreview(this,'full_image3');"}  %>
      </td>
      <td>
        <% if @snapshot.full_image3? %>
          <%= image_tag @snapshot.full_image3, :id => "full_image3", :width=>"150px" %>
        <% else %>
          <%= image_tag("no_img_160_120.gif", :id => "full_image3", :alt => "uploaded image") %>
        <% end %>
      </td>
    </tr>
  </table>

  <%= f.input :full_pdf, :as => :file %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sample_ror_admin/app/views/snapshots/_topic_fields.html.erb
<div class="fields">

  <%= f.input :topic_id, :collection => Topic.all %>
  <%= f.hidden_field :_destroy %>
  <%= link_to_function "remove", "remove_fields(this)" %>

</div>

sample_ror_admin/app/views/snapshots/_topicization_fields.html.erb
<div class="fields row_t">
  <table>
    <tr>
      <td><%= f.input :topic_id, :collection => Topic.all, :include_blank => false %></td>
      <td><%= link_to_remove_fields "remove", f %></td>
    </tr>
  </table>
</div>

sample_ror_admin/app/views/snapshots/edit.html.erb
<h3>Edit Snapshot</h3>
<%= render 'form' %>

<%= link_to 'Show', @snapshot %> |
<%= link_to 'Back', snapshots_path %>

sample_ror_admin/app/views/snapshots/index.html.erb
</style>

<div class="row-fluid">
  <ul class="thumbnails">
    <% @snapshots.each do |snapshot| %>
    <li class="span10" >
      <div class="thumbnail img row_t">
        <div class="cell_t" style="width:30%" >
        <% if snapshot.thumb_image? %>
          <%= link_to image_tag(snapshot.thumb_image), snapshot %>
        <% else %>
          <%= link_to image_tag('no_img_160_120.gif'), snapshot %>
        <% end %>
        <div class="desc"><%= snapshot.download_count %> Downloads</div>
        </div>
        <div class="caption cell_t"  >
          <h3><%= snapshot.title %></h3> 
          <p>Published on : <%= snapshot.publication_date %></p>
          <p>Authors : <%= snapshot.authors %></p>
          <p>Abstract : <%= snapshot.abstract %></p>
          <p>
            <ul class="nav nav-pills" style="float: right">
              <li>
                <%= link_to 'View', snapshot %>
              </li>
              <li>
                <a href="<%= edit_snapshot_path(snapshot) %>" >Edit</a>
              </li>
              <li class="disabled">
                <%= link_to 'Destroy', snapshot, method: :delete, data: { confirm: 'Are you sure?' } %>
              </li>
            </ul>
          </p>
        </div>
      </div>
    </li>
  <% end %>
  </ul>
</div>

sample_ror_admin/app/views/snapshots/new.html.erb
<h3>New Snapshot</h3>
<%= render 'form' %>

<%= link_to 'Back', snapshots_path %>

sample_ror_admin/app/views/snapshots/show.html.erb
<p>
  <b>Title:</b>
  <%= @snapshot.title %>
</p>

<p>
  <b>Publication date:</b>
  <%= @snapshot.publication_date %>
</p>

<p>
  <b>Disporder:</b>
  <%= @snapshot.disporder %>
</p>

<p>
  <b>Displayed:</b>
  <%= @snapshot.displayed %>
</p>

<p>
  <b>Authors:</b>
  <%= @snapshot.authors %>
</p>

<p>
  <b>Abstract:</b>
  <%= @snapshot.abstract %>
</p>

<p>
  <b>Popularity:</b>
  <%= @snapshot.popularity %>
</p>

<p>
  <b>Download count:</b>
  <%= @snapshot.download_count %>
</p>

<p>
<b>Under Topics:</b>
<ul>
  <% for topicization in @snapshot.topicizations %>
    <li>Topic : <%=h topicization.topic.name %></li>
  <% end %>
</ul>
</p>

<p>
  <b>Thumb image:</b>
  <%= image_tag(@snapshot.thumb_image, :width => "150px") if @snapshot.thumb_image? %>
</p>

<p>
  <b>Cover image:</b>
  <%= image_tag(@snapshot.cover_image, :width => "150px") if @snapshot.cover_image? %>
</p>

<p>
  <b>Full image1:</b>
  <%= image_tag(@snapshot.full_image1, :width => "150px") if @snapshot.full_image1? %>
</p>

<p>
  <b>Full image2:</b>
  <%= image_tag(@snapshot.full_image2, :width => "150px") if @snapshot.full_image2? %>
</p>

<p>
  <b>Full image3:</b>
  <%= image_tag(@snapshot.full_image3, :width => "150px") if @snapshot.full_image3? %>
</p>

<p>
  <b>Full pdf:</b>
  <%= @snapshot.full_pdf %>
</p>


<%= link_to 'Edit', edit_snapshot_path(@snapshot) %> |
<%= link_to 'Back', snapshots_path %>

sample_ror_admin/app/views/topics/_form.html.erb
<%= simple_form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :name %>
    <%= f.input :displayed %>
    <%= f.input :disporder %>
    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sample_ror_admin/app/views/topics/edit.html.erb
<h3>Editing topic</h3>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

sample_ror_admin/app/views/topics/index.html.erb
<table class="table table-hover" >
  <tr>
    <th>Name</th>
    <th>Disporder</th>
    <th>Displayed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.name %></td>
    <td><%= topic.disporder %></td>
    <td><%= topic.displayed %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

sample_ror_admin/app/views/topics/new.html.erb
<h3>New topic</h3>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

sample_ror_admin/app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @topic.name %>
</p>

<p>
  <b>Disporder:</b>
  <%= @topic.disporder %>
</p>

<p>
  <b>Displayed:</b>
  <%= @topic.displayed %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>